export const SEQUELIZE = 'SEQUELIZE';

export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const USER_LOGINRECORDS_REPOSITORY = 'USER_LOGINRECORDS_REPOSITORY';
export const USER_PROFILES_REPOSITORY = 'USER_PROFILES_REPOSITORY';
export const USER_ROLES_REPOSITORY = 'USER_ROLES_REPOSITORY';
export const USER_SUBSCRIPTIONS_REPOSITORY = 'USER_SUBSCRIPTIONS_REPOSITORY';
export const PAYMENTS_REPOSITORY = 'PAYMENTS_REPOSITORY';
export const USER_PLATFORMS_REPOSITORY = 'USER_PLATFORMS_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const VETS_REPOSITORY = 'VETS_REPOSITORY';
